// pianoConfig.ts
import { Key } from "@/types/piano.types";

export const WHITE_KEYS = ["C", "D", "E", "F", "G", "A", "B"];

export const BLACK_KEY_NAMES: {
  [key: number]: { sharp: string; flat: string };
} = {
  0: { sharp: "C#", flat: "Db" },
  1: { sharp: "D#", flat: "Eb" },
  3: { sharp: "F#", flat: "Gb" },
  4: { sharp: "G#", flat: "Ab" },
  5: { sharp: "A#", flat: "Bb" },
};

export const KEYS: Key[] = [
  {
    type: "white",
    label: `${WHITE_KEYS[0]}`,
    value: [WHITE_KEYS[0]],
    octave: 4,
    midiKey: 60,
    keyboardKey: "a",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[0].sharp}/${BLACK_KEY_NAMES[0].flat}`,
    value: [BLACK_KEY_NAMES[0].sharp, BLACK_KEY_NAMES[0].flat],
    octave: 4,
    midiKey: 61,
    keyboardKey: "w",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[1]}`,
    value: [WHITE_KEYS[1]],
    octave: 4,
    midiKey: 62,
    keyboardKey: "s",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[1].sharp}/${BLACK_KEY_NAMES[1].flat}`,
    value: [BLACK_KEY_NAMES[1].sharp, BLACK_KEY_NAMES[1].flat],
    octave: 4,
    midiKey: 63,
    keyboardKey: "e",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[2]}`,
    value: [WHITE_KEYS[2]],
    octave: 4,
    midiKey: 64,
    keyboardKey: "d",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[3]}`,
    value: [WHITE_KEYS[3]],
    octave: 4,
    midiKey: 65,
    keyboardKey: "f",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[3].sharp}/${BLACK_KEY_NAMES[3].flat}`,
    value: [BLACK_KEY_NAMES[3].sharp, BLACK_KEY_NAMES[3].flat],
    octave: 4,
    midiKey: 66,
    keyboardKey: "t",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[4]}`,
    value: [WHITE_KEYS[4]],
    octave: 4,
    midiKey: 67,
    keyboardKey: "g",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[4].sharp}/${BLACK_KEY_NAMES[4].flat}`,
    value: [BLACK_KEY_NAMES[4].sharp, BLACK_KEY_NAMES[4].flat],
    octave: 4,
    midiKey: 68,
    keyboardKey: "y",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[5]}`,
    value: [WHITE_KEYS[5]],
    octave: 4,
    midiKey: 69,
    keyboardKey: "h",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[5].sharp}/${BLACK_KEY_NAMES[5].flat}`,
    value: [BLACK_KEY_NAMES[5].sharp, BLACK_KEY_NAMES[5].flat],
    octave: 4,
    midiKey: 70,
    keyboardKey: "u",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[6]}`,
    value: [WHITE_KEYS[6]],
    octave: 4,
    midiKey: 71,
    keyboardKey: "j",
  },
  // Second octave (octave 5)
  {
    type: "white",
    label: `${WHITE_KEYS[0]}`,
    value: [WHITE_KEYS[0]],
    octave: 5,
    midiKey: 72,
    keyboardKey: "A",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[0].sharp}/${BLACK_KEY_NAMES[0].flat}`,
    value: [BLACK_KEY_NAMES[0].sharp, BLACK_KEY_NAMES[0].flat],
    octave: 5,
    midiKey: 73,
    keyboardKey: "W",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[1]}`,
    value: [WHITE_KEYS[1]],
    octave: 5,
    midiKey: 74,
    keyboardKey: "S",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[1].sharp}/${BLACK_KEY_NAMES[1].flat}`,
    value: [BLACK_KEY_NAMES[1].sharp, BLACK_KEY_NAMES[1].flat],
    octave: 5,
    midiKey: 75,
    keyboardKey: "E",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[2]}`,
    value: [WHITE_KEYS[2]],
    octave: 5,
    midiKey: 76,
    keyboardKey: "D",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[3]}`,
    value: [WHITE_KEYS[3]],
    octave: 5,
    midiKey: 77,
    keyboardKey: "F",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[3].sharp}/${BLACK_KEY_NAMES[3].flat}`,
    value: [BLACK_KEY_NAMES[3].sharp, BLACK_KEY_NAMES[3].flat],
    octave: 5,
    midiKey: 78,
    keyboardKey: "T",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[4]}`,
    value: [WHITE_KEYS[4]],
    octave: 5,
    midiKey: 79,
    keyboardKey: "G",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[4].sharp}/${BLACK_KEY_NAMES[4].flat}`,
    value: [BLACK_KEY_NAMES[4].sharp, BLACK_KEY_NAMES[4].flat],
    octave: 5,
    midiKey: 80,
    keyboardKey: "Y",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[5]}`,
    value: [WHITE_KEYS[5]],
    octave: 5,
    midiKey: 81,
    keyboardKey: "H",
  },
  {
    type: "black",
    label: `${BLACK_KEY_NAMES[5].sharp}/${BLACK_KEY_NAMES[5].flat}`,
    value: [BLACK_KEY_NAMES[5].sharp, BLACK_KEY_NAMES[5].flat],
    octave: 5,
    midiKey: 82,
    keyboardKey: "U",
  },
  {
    type: "white",
    label: `${WHITE_KEYS[6]}`,
    value: [WHITE_KEYS[6]],
    octave: 5,
    midiKey: 83,
    keyboardKey: "J",
  },
];
